version: "3"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pair_dance_dev

volumes:
  data:
    driver: local
