version: "2.1"
orbs:
  node: circleci/node@5.0.3
  gcp-gcr: circleci/gcp-gcr@0.15.1
jobs:
  build_phoenix:
    docker:
      - image: circleci/elixir:1.13-node
      - image: cimg/postgres:15.0
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test --exclude e2e
  build_image:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: pair_dance
          no_output_timeout: 20m
          registry-url: eu.gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: pair_dance
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build:
    jobs:
      - build_phoenix
      - build_image
