version: "2.1"
orbs:
  node: circleci/node@5.0.3
  gcp-gcr: circleci/gcp-gcr@0.15.1
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
  gcp-cli: circleci/gcp-cli@3.1.0
jobs:
  build_app:
    docker:
      - image: circleci/elixir:1.13-node
      - image: cimg/postgres:15.0
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test --exclude e2e
  build_image:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: pair_dance
          no_output_timeout: 20m
          registry-url: eu.gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: pair_dance
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - gcp-cloud-run/init
      - gcp-cloud-run/deploy:
          image: eu.gcr.io/${GOOGLE_PROJECT_ID}/pair_dance:latest
          platform: managed
          region: ${GOOGLE_COMPUTE_ZONE}
          service-name: pair-dance-app
          unauthenticated: true
  prune_unused_images:
    docker:
      - image: google/cloud-sdk:435.0.1-alpine
    steps:
      - checkout
      - run:
          command: |
            echo $GCLOUD_SERVICE_KEY > ./key.json

            gcloud auth activate-service-account ci-service-account@pair-dance-370619.iam.gserviceaccount.com --key-file=./key.json --project=$GOOGLE_PROJECT_ID

            cd ./infrastructure
            ./prune_docker_images
  migrate:
    executor: gcp-cli/default
    steps:
      - gcp-cli/setup:
          version: 435.0.1
      - run: gcloud beta run jobs execute pair-dance-db-migration --region ${GOOGLE_COMPUTE_ZONE} --wait
workflows:
  build:
    jobs:
      - build_app
      - build_image:
          requires:
            - build_app
      - prune_unused_images:
          requires:
            - build_image
      - migrate:
          requires:
            - build_image
      - deploy:
          requires:
            - migrate
