version: "2.1"
orbs:
  node: circleci/node@5.0.3
  gcp-gcr: circleci/gcp-gcr@0.15.1
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
jobs:
  build_app:
    docker:
      - image: circleci/elixir:1.13-node
      - image: cimg/postgres:15.0
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test --exclude e2e
  build_image:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: pair_dance
          no_output_timeout: 20m
          registry-url: eu.gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: pair_dance
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - gcp-cloud-run/init
      - gcp-cloud-run/deploy:
          image: eu.gcr.io/${GOOGLE_PROJECT_ID}/pair_dance:latest
          platform: managed
          region: ${GOOGLE_COMPUTE_ZONE}
          service-name: pair-dance-app
          unauthenticated: true

  migrate:
    docker:
      - image: eu.gcr.io/${GOOGLE_PROJECT_ID}/pair_dance:latest
    steps:
      - run:
          command: |
            mix ecto.migrate
workflows:
  build:
    jobs:
      - migrate
      - build_app:
          requires:
            - migrate
      - build_image:
          requires:
            - build_app
      - deploy:
          requires:
            - build_image
