
version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  build_phoenix:
    docker:
      - image: circleci/elixir:1.13-node
      - image: cimg/postgres:15.0
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
  deploy:
    docker:
      - image: circleci/elixir:1.13-node
    environment:
      APP_NAME: pair_dance
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3 python3-pip git-core curl
      - run:
          command: |
            pip3 install gigalixir --user
            echo "export PATH=\$PATH:$(python3 -m site --user-base)/bin" >> ~/.bash_profile
            . ~/.bash_profile
      - run: gigalixir login -e "$GIGALIXIR_EMAIL" -y -p "$GIGALIXIR_PASSWORD"
      - run: gigalixir create --name $APP_NAME || gigalixir git:remote $APP_NAME
      - run: "git -c http.extraheader='GIGALIXIR-CLEAN: true' push gigalixir `git subtree split main`:refs/heads/master --force"
  keep_alive:
    docker:
      - image: cimg/base:2021.04
    working_directory: ~/pair_dance
    steps:
      - checkout:
          path: ~/pair_dance
      - run: ./keep-alive
parameters:
  run-schedule:
      type: boolean
      default: false
workflows:
  build:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - build_phoenix
      - deploy:
          requires:
            - build_phoenix
  keep_alive:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - keep_alive
